apiVersion: apps/v1

kind: Deployment

metadata:
  name: dart-backend-deployment

spec:
  selector:
    matchLabels:
      app: dart-backend

  template:
    metadata:
      labels:
        app: dart-backend

    spec:
      hostNetwork: false
      imagePullSecrets:
        - name: regcred
      containers:
        - name: dart-backend
          image: it-4-us/dart-backend:$(DOCKER_IMAGE_TAG)
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

---

apiVersion: v1

kind: Service

metadata:
  name: dart-backend-service

spec:
  selector:
    app: dart-backend

  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

---

apiVersion: networking.k8s.io/v1

kind: Ingress

metadata:
  name: dart-backend-ingress

spec:
  rules:
    - host: tnr-dart.fria.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dart-backend-service
                port:
                  number: 80
