server:
  port: 8080
spring:
  application:
    name: todoapp
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://dart-postgres:5432/dart
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

springdoc:
  swagger-ui:
  url: /openapi.yaml