name: Build

on:
  push:
    branches:
      - main
      - development

jobs:
  cd:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Maven Action
        uses: stCarolas/setup-maven@v4.5
        with:
            maven-version: 3.8.6

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package 