name: Build

on:
  pull_request:
    branches:
      - main
      - development

jobs:
  cd:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: ./mvnw --batch-mode --update-snapshots package

      run:
        working-directory: frontend

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
        run: npm i
        run: npm ci
        run: npm run build --if-present
        run: eslint . --ext .js,.jsx,.ts,.tsx
        run: npm test
 
