name: Build

on:
  pull_request:
    branches:
      - main
      - development

jobs:
  cd:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Change wrapper permissions
        run: chmod +x ./mvnw

      - name: Build with Maven
        run: ./mvnw --batch-mode --update-snapshots package 